# UCS420: Cognitive Computing — Assignment 3
## Pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nipun\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\nipun\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Question 1: Create the dataset

In [2]:

import pandas as pd


data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital_Status": ["Single","Married","Single","Married","Divorced",
                        "Married","Divorced","Single","Married","Single"],
    "Taxable_Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Question 2: Locate rows 0, 4, 7, 8

In [3]:
df.loc[[0, 4, 7, 8]]

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Question 3: Navigating the DataFrame

**1. Rows from index 3 to 7 (inclusive, using `.loc`)**

In [4]:
df.loc[3:7]

   Tid Refund Marital_Status Taxable_Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

**2. Rows 4 to 8, columns 2 to 4 (position-based, using `.iloc`)**

In [5]:
# .iloc excludes the stop, so 4:9 gives rows 4-8 and 2:4 gives columns at position 2 and 3
df.iloc[4:9, 2:4]

  Marital_Status Taxable_Income
4       Divorced            95K
5        Married            60K
6       Divorced           220K
7         Single            85K
8        Married            75K

**3. All rows, column index 1 to 3, including index 3**

In [6]:
# stop is exclusive in iloc, so 1:4 is needed to include column index 3
df.iloc[:, 1:4]

  Refund Marital_Status Taxable_Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Question 4: Read a CSV and display the first five rows

In [7]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\nipun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from sklearn.datasets import load_iris

iris_raw = load_iris(as_frame=True)
iris_df = iris_raw.frame
iris_df["species"] = iris_raw.target_names[iris_raw.target]
iris_df.to_csv("iris.csv", index=False)

iris = pd.read_csv("iris.csv")
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

## Question 5: Delete row 4 and column 3, display result

In [9]:
iris_mod = iris.drop(index=4)          # delete row with label 4
iris_mod = iris_mod.drop(iris_mod.columns[3], axis=1)  # delete column at position 3

iris_mod.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  target species
0                5.1               3.5                1.4       0  setosa
1                4.9               3.0                1.4       0  setosa
2                4.7               3.2                1.3       0  setosa
3                4.6               3.1                1.5       0  setosa
5                5.4               3.9                1.7       0  setosa

## Question 6: Employees dataset

In [10]:
emp_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

emp_df = pd.DataFrame(emp_data)
emp_df.to_csv("employees.csv", index=False)

emp_df = pd.read_csv("employees.csv")
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**a) Shape of the DataFrame**

In [11]:
emp_df.shape

(5, 10)

**b) Summary — dtypes and non-null counts**

In [12]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 528.0 bytes

**c) Descriptive statistics**

In [13]:
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

**d) First 5 rows and last 3 rows**

In [14]:
print("First 5:")
display(emp_df.head())
print("Last 3:")
display(emp_df.tail(3))

First 5:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**e) Key statistics**

In [15]:
avg_salary = emp_df["Salary"].mean()
total_bonus = emp_df["Bonus"].sum()
youngest_age = emp_df["Age"].min()
highest_rating = emp_df["Rating"].max()

print(f"i.   Average salary: {avg_salary}")
print(f"ii.  Total bonus paid: {total_bonus}")
print(f"iii. Youngest employee's age: {youngest_age}")
print(f"iv.  Highest rating: {highest_rating}")

i.   Average salary: 60000.0
ii.  Total bonus paid: 27500
iii. Youngest employee's age: 28
iv.  Highest rating: 4.7

**f) Sort by Salary, descending**

In [16]:
emp_df.sort_values("Salary", ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

**g) Performance category column**

In [17]:
def categorize(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

emp_df["Performance_Category"] = emp_df["Rating"].apply(categorize)
emp_df[["Name", "Rating", "Performance_Category"]]

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

**h) Missing values**

In [18]:
emp_df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

**i) Rename Employee_ID → ID**

In [19]:
emp_df = emp_df.rename(columns={"Employee_ID": "ID"})
emp_df.columns.tolist()

['ID',
 'Name',
 'Department',
 'Age',
 'Salary',
 'Years_of_Experience',
 'Joining_Date',
 'Gender',
 'Bonus',
 'Rating',
 'Performance_Category']

**j) Filter employees**

In [20]:
print("i. More than 5 years of experience:")
display(emp_df[emp_df["Years_of_Experience"] > 5])

print("ii. Belong to IT department:")
display(emp_df[emp_df["Department"] == "IT"])

i. More than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

ii. Belong to IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

**k) Add Tax column (10% of Salary)**

In [21]:
emp_df["Tax"] = emp_df["Salary"] * 0.10
emp_df[["Name", "Salary", "Tax"]]

      Name  Salary     Tax
0    Alice   50000  5000.0
1      Bob   70000  7000.0
2  Charlie   65000  6500.0
3    Diana   55000  5500.0
4   Edward   60000  6000.0

**l) Save the modified DataFrame to a new CSV**

In [22]:
emp_df.to_csv("employees_modified.csv", index=False)
print("Saved to employees_modified.csv")

Saved to employees_modified.csv